# Generated by Django 6.0.5 on 2026-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_message_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Сообщение зашифровано E2E'),
        ),
    ]
