# Generated by Django 6.0.5 on 2026-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='text_size',
            field=models.PositiveSmallIntegerField(default=14, help_text='Font size in pixels (12-22)'),
        ),
    ]
