# Generated by Django 6.0.5 on 2026-06-26 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=10)),
                ('auto_translate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_language', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('text_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see_phone_number', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='contacts', max_length=20)),
                ('see_profile_photo', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('see_last_seen', models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('auto_delete_messages', models.BooleanField(default=False)),
                ('message_ttl_days', models.PositiveIntegerField(blank=True, help_text='Автоудаление сообщений через N дней', null=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
