# Generated by Django 6.0.5 on 2026-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonecode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='phonecode',
            new_name='users_phone_phone_n_7b141c_idx',
            old_name='users_phone_phone_n_b6c7c9_idx',
        ),
    ]
